### ISSUE TITLE
Build failing "libpng support requested but library not found"

### ISSUE THREAD

**Issue by reines** [WritingMinds/ffmpeg-android#1]
I am attempting to build this against Android L using ABI version 4.9.

```
SUPPORTED_ARCHITECTURES=(armeabi-v7a armeabi-v7a-neon)
ANDROID_NDK_ROOT_PATH=~/Android/ndk
ANDROID_API_VERSION=L
NDK_TOOLCHAIN_ABI_VERSION=4.9
```

This is on an Azure VM, running a fresh install of Ubuntu Server 14.04. 

I have installed the following extra packages:

```
yasm bash patch make gawk aclocal automake libtool
```

build log: https://gist.github.com/reines/e3584625d1b3d92e1bd2

**Comment by minwei0829** [comment]
I met the same problem, how did you fix it.
