### ISSUE TITLE
How can I convert my APK to 64-bit architecture ?

### ISSUE THREAD

**Issue by bhautikforesight027** [WritingMinds/ffmpeg-android#106]
Play store didn't accept my app because of 64-bit architecture validation so what can I do I have already try other libraries but my command didn't work there and also I request (Mail through) to @hiteshsondhi88 and Wiritingminds but they didn't replied so what next if any one know then please let me know. I am currently using implementation 'com.writingminds:FFmpegAndroid:0.3.2' this library.

there mailid is : 
hitesh@cropsly.com
contact@writingminds.com

Thanks in advance...

You can also contact me at :
lathiyabhautik023@gmail.com (always available )
bhautik@foresighttechnologies.in (in office hours)

**Comment by manueljoseph1995** [comment]
Did you resolved this issue. I am also having the same problem here. I am expecting a new release for this library with 64 bit compatibility.

**Comment by bhautikforesight027** [comment]
@manueljoseph1995  Yes i solved this but i move on from WritingMinds and i used https://github.com/bravobit/FFmpeg-Android this library for ffmpeg and this library with 64 bit compatibility given me
