### ISSUE TITLE
Could you please update the library to work with ffmpeg 2.8.1?

### ISSUE THREAD

**Issue by MrBokeh** [WritingMinds/ffmpeg-android#22]
Could you please update the library to work with ffmpeg 2.8.1?

**Comment by MrBokeh** [comment]
I have tried to complied the library to 2.8.1 on the latest Ubuntu Desktop 14.04 LTS but it throws many errors and deprecated warnings during compilation. So the ffmpeg executable files that it compiled won't work on Android anymore.

**Comment by endryha** [comment]
Is it possible to upgrade to 2.6? Anybody knows?
