### ISSUE TITLE
libpng-1.6.21 is missing

### ISSUE THREAD

**Issue by tinnnysu** [WritingMinds/ffmpeg-android#37]
ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.21.tar.xz is not avaliable

**Comment by FloridaStream** [comment]
try
`ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.23.tar.xz`

**Comment by tinnnysu** [comment]
Thanks
