### ISSUE TITLE
How to make all the static libraries to a shared library?

### ISSUE THREAD

**Issue by shenzhiguo** [WritingMinds/ffmpeg-android#61]
I'd want make following static libraries to a shred library.What's code add to ```android_build.sh``` can make it success?
```
libavcodec.a  
libavdevice.a  
libavfilter.a  
libavformat.a  
libavutil.a  
libpostproc.a  
libswresample.a  
libswscale.a
```

**Comment by Huskera** [comment]
try to update --disable-shared to --enable-shared in ffmpeg_build.sh
