### ISSUE TITLE
undefined reference to ‘main’ when build shared library

### ISSUE THREAD

**Issue by milkywayriver** [WritingMinds/ffmpeg-android#62]
when i –enable-static,every thing was just fine,and i got all the .a file generated,but when i –enable-shared,i get these error:

/mnt/c/Users/john/Documents/ffmpeg-android/toolchain-android/sysroot/usr/lib/crtbegin_dynamic.o:crtbegin_dynamic.c:function _start: error: undefined reference to ‘main’
collect2: error: ld returned 1 exit status
make: *** [libavutil/libavutil-55.so] Error 1

can you help me,please?
thank you!

my config script :

./configure \
–target-os=”$TARGET_OS” \
–cross-prefix=”$CROSS_PREFIX” \
–arch=”$NDK_ABI” \
–cpu=”$CPU” \
–enable-runtime-cpudetect \
–enable-cross-compile \
–sysroot=”$NDK_SYSROOT” \
–disable-debug \
–disable-avdevice \
–disable-avformat \
–disable-swresample \
–disable-swscale \
–disable-postproc \
–disable-ffserver \
–disable-ffmpeg \
–disable-ffplay \
–disable-ffprobe \
–disable-encoders \
–disable-decoders \
–disable-demuxers \
–disable-muxers \
–disable-doc \
–enable-shared \
–disable-static \
–pkg-config=”${2}/ffmpeg-pkg-config” \
–prefix=”${2}/build/${1}” \
–extra-cflags=”-Os -I${TOOLCHAIN_PREFIX}/include $CFLAGS” \
–extra-ldflags=”-L${TOOLCHAIN_PREFIX}/lib $LDFLAGS” \
–extra-libs=”-lpng -lexpat -lm” \
–extra-cxxflags=”$CXX_FLAGS” || exit 1

make -j${NUMBER_OF_CORES} && make install

**Comment by Huskera** [comment]
try to remove  -Wl,-z,now -pie from LDFLAGS in settings.sh

**Comment by milkywayriver** [comment]
great! it works.
thank you!

**Comment by Kondenko** [comment]
I'm facing the same issue, but I've got --enable-static and --disable-shared and no flags mentioned above. Any ideas why this is happening?

My build script is as follows:

#!/bin/sh

ARCH=arm
API=17
CPU=armv7

NDK=~/Android/SDK/ndk
TOOLCHAIN=$NDK/toolchains/arm-linux-androideabi
SYSROOT=$TOOLCHAIN/sysroot
CROSS_PREFIX=$TOOLCHAIN/bin/arm-linux-androideabi- 


make_or_die() {
    make -j $(nproc) || exit
    sudo make install || exit
}

export PATH=$PATH:$TOOLCHAIN/bin
export USE_SDL=/usr/local/bin/sdl2-config
export CC="arm-linux-androideabi-clang"
export CXX="arm-linux-androideabi-clang++"

./configure \
    --prefix=$FFMPEG_PREFIX \
    --cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
    --target-os=android \
    --arch=arm \
    --sysroot=$SYSROOT \
    --cc=$CC \
    --cxx=$CXX \
    --pkg-config="pkg-config" \
    --pkg-config-flags="--static" \
    --enable-cross-compile \
    --enable-ffplay \
    --enable-sdl2 \
    --enable-static \
    --enable-pthreads \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-runtime-cpudetect \
    --enable-hardcoded-tables \
    --enable-pic \
    --enable-libx264 \
    --disable-ffprobe \
    --disable-ffmpeg \
    --disable-ffserver \
    --disable-shared \
    --disable-yasm \
    --disable-debug \
    --disable-doc \
    --disable-opencl \
    --disable-symver \
    --extra-cflags="-I$TOOLCHAIN/include -I$X264 -I$SDL/include -lSDL2 -lm -ldl -lsndio -lpthread -lrt -D_REENTRANT -D__ANDROID_API__=$API -Os -fpic -marm -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -fPIE" \
    --extra-ldflags="-L$TOOLCHAIN/lib -L$X264 -L$SDL_PREFIX/android/obj/local/armeabi-v7a -llog -landroid -lEGL" || exit
