### ISSUE TITLE
Fail to load font and add subtitle

### ISSUE THREAD

**Issue by tzutalin** [WritingMinds/ffmpeg-android#73]
Hi,
  Thanks for building the prebuilt binaries. The basic sample commands can work on my arm device. However, I tried to add subtitles to my video, then it fails. Do you have any idea?

OS: Anroid L
CPU arch:  Arm
I push [fonts.conf ](https://forum.videohelp.com/attachments/30930-1427645321/fonts.zip)to /sdcard/ and assign it to FONTCONFIG_FILE, then run it using below commands:
```


$ FONTCONFIG_FILE=/sdcard/fonts.conf ./ffmpeg -i /sdcard/test.mp4 -vf subtitles=/sdcard/sample.srt /sdcard/output.mp4
```

Error logs:
```
[Parsed_subtitles_0 @ 0xb836e8d0] No valid fontconfig configuration found!
[Parsed_subtitles_0 @ 0xb836e8d0] can't find selected font provider
```

**Comment by tzutalin** [comment]
Fixed. The fonts.conf I download is invalid.

**Comment by uscmsr** [comment]
What `fonts.conf` file did you end up using?

**Comment by uscmsr** [comment]
nvm. see issue #18
