### ISSUE TITLE
Error Building Libpng with Undefined Reference to 'stderr'

### ISSUE THREAD

**Issue by ChillingVan** [WritingMinds/ffmpeg-android#79]
undefined reference to 'stderr'
And other stdio.h files are not found.
These errors are showed when building the code under /contrib of libpng. 
The code of /contrib is not necessary to build. How can I cancel building of /contrib ?
Can I add parameters to the libpng_build.sh for the Configure?

Could anyone help?

**Comment by johnothwolo** [comment]
I think it has to do with [this](https://github.com/android-ndk/ndk/issues/445) and [this](https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md)
Try my [patch](https://gist.github.com/johnothwolo/d5c0adfb202bb4d733f5fdc85d62012e#file-lib_png_patch-patch)

**Comment by ChillingVan** [comment]
Thanks
