### ISSUE TITLE
Create or change wav file to Wav, 16000Hz mono

### ISSUE THREAD

**Issue by channae** [WritingMinds/ffmpeg-android#89]
Hi,

I'm merging multiple wav files using following command, 

` -f concat -safe 0 -i /storage/emulated/0/AudioClipsForSpeakerRecognition/1/speaker_1_segments.txt -c copy /storage/emulated/0/AudioClipsForSpeakerRecognition/1/speaker_1.wav`

How can I get the output wav file in 16000Hz mono?

Thanks,

**Comment by channae** [comment]
I managed to do this with following command, 

`-f concat -safe 0 -i /storage/emulated/0/AudioClipsForSpeakerRecognition/1/speaker_1_segments.txt -ac 1 -ar 16000 /storage/emulated/0/AudioClipsForSpeakerRecognition/1/speaker_1.wav`

**Comment by WangkeqiangS** [comment]
> 我设法通过以下命令来做到这一点，
> 
> `-f concat -safe 0 -i /storage/emulated/0/AudioClipsForSpeakerRecognition/1/speaker_1_segments.txt -ac 1 -ar 16000 /storage/emulated/0/AudioClipsForSpeakerRecognition/1/speaker_1.wav`

您好  您可以正常拼接wav格式的音频嘛？
